name: Label PRs

on:
  - pull_request_target

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_linked_issue
        with:
          query: |
            query issue($owner:String!,$repo:String!,$pr:String!) {
              repository(owner:$owner,name:$repo) {
                pullRequest(number: $pr) {
                  closingIssuesReferences (first: 50) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.name }}
            repo: ${{ github.event.repository.name }}
            pr: ${{ github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: count_edges
        run: |
          jq '.edges[] | length' << ${{ fromJson(steps.get_linked_issue.outputs.data).repository.pullRequest.closingIssuesReferences }})
        