name: Label PRs

on:
  - pull_request_target

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_linked_issue
        with:
          query: |
            query issue($owner:String!,$repo:String!,$pr:Int!) {
              repository(owner:$owner,name:$repo) {
                pullRequest(number: $pr) {
                  closingIssuesReferences (first: 50) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.repository_owner }}
            repo: ${{ github.event.repository.name }}
            pr: ${{ github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: count_edges
        env:
          GH_DETAILS: ${{ steps.get_linked_issue.outputs.data }}
        run: |
          echo "$GH_DETAILS" | jq '.repository.pullRequest.closingIssuesReferences.edges | length'

        